export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
export const DEL_PRODUCT_CART = 'DEL_PRODUCT_CART';
export const EMPTY_PRODUCT_CART = 'EMPTY_PRODUCT_CART';
export const FETCH_DATA = 'FETCH_DATA';
export const LOADING = 'LOADING';
export const CLOSE_PRODUCT_ALERT = 'CLOSE_PRODUCT_ALERT';
export const UPDATE_USER_NAVBAR = 'UPDATE_USER_NAVBAR';